### ISSUE TITLE
httperf segaults on macosx 10.7.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [httperf/httperf#18]
```
What steps will reproduce the problem?
1. Run httperf as follows httperf  --timeout=10   --server=*host*  --port=80 
--wlog=y,requests_httperf_Hindi.txt --uri=/ --rate=200 --num-conns=2000 
--num-calls=1 --client=1/3 
2. outputs Segmentation fault: 11
3.

What is the expected output? What do you see instead?
I expect the test to go on but instead it segfaults.
However if I lower rate to some 100 it does not segfault.



What version of the product are you using? On what operating system?
v0.9

Please provide any additional information below.
ulimit on the host
ulimit -n
10000
uname -a
Darwin degreethem-lm 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 
PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64


```

Original issue reported on code.google.com by `jithin1...@gmail.com` on 19 Feb 2013 at 1:02

**Comment by refried** [comment]
+1

**Comment by refried** [comment]
```
==11998== Invalid read of size 4
==11998==    at 0x100004B13: core_loop (core.c:1506)
==11998==    by 0x100002781: main (httperf.c:1312)
==11998==  Address 0x41d5beb2e1a5f0fe is not stack'd, malloc'd or (recently) free'd
```
using  cc88843

**Comment by erikarn** [comment]
Does anyone have a patch for it? I'm out of cycles right now to work on it!

**Comment by refried** [comment]
Not yet, trying to understand the application structure.  At first blush it seems to be reading way off the end of sp_to_conn

**Comment by refried** [comment]
Put some time into it, but couldn't figure it out.  Ended up switching to https://github.com/tsenart/vegeta and will probably stay there even though httperf's command-line seems easier.

**Comment by erikarn** [comment]
Ok!

ok, so that sd_to_conn[] is a possible problem. It doesn't look like the
code setting up sd_to_conn[] contents and reallocating things is working on
macosx - I bet that it's overflowing that array :(

How are you reproducing it? I think I can reproduce this pretty easily and
likely replace all of that select() code with something slightly less
stupid.

Thanks!



-adrian

**Comment by refried** [comment]
Later I was getting "Invalid arguments" or something as the error code from
select(). Unfortunately macosx doesnt seem to have an equivalent to
explain_select we can use in linux to get more info.

as far as reproducing it, it would crash any time the request rate or
request totals were very high. I wanted to use thousands but could only use
tens successfully. i can post the exact commandline later, but it does seem
to be a problem of the core functionality; using connections.

I bet if you had a simplification for that section, the problem would go
away... maybe?

**Comment by refried** [comment]
By the way, sometimes it seemed to crash even when not overflowing that
array. Sorry I know this is too vague to be helpful.

**Comment by refried** [comment]
Ok, maybe this will be helpful:

Given:

```
10:44 lawn-128-61-79-214:/tmp/httperf (master)$ git diff
diff --git a/src/core.c b/src/core.c
index bb4929e..5f77f61 100755
--- a/src/core.c
+++ b/src/core.c
@@ -1126,6 +1126,7 @@ core_connect(Conn * s)
 
                old_size = alloced_sd_to_conn * sizeof(sd_to_conn[0]);
                alloced_sd_to_conn += 2048;
+               printf("alloced_sd_to_conn = %d\n", alloced_sd_to_conn);
                size = alloced_sd_to_conn * sizeof(sd_to_conn[0]);
                if (sd_to_conn)
                        sd_to_conn = realloc(sd_to_conn, size);
@@ -1502,6 +1503,7 @@ core_loop(void)
                             * only handle sockets that
                             * haven't timed out yet
                             */
+                           printf("using connection %d\n", sd);
                            conn = sd_to_conn[sd];
                            conn_inc_ref(conn);
 
10:44 lawn-128-61-79-214:/tmp/httperf (master)$ 
```

then:
```
10:43 lawn-128-61-79-214:/tmp/httperf/build/src (master)$ ./httperf --hog --server localhost --port 11080 --uri http://localhost:11080/fasor-api/v1/crc/meeting/1 --num-conn 10000 --ra 1000 --timeout 1
httperf --hog --timeout=1 --client=0/1 --server=localhost --port=11080 --uri=http://localhost:11080/fasor-api/v1/crc/meeting/1 --rate=1000 --send-buffer=4096 --recv-buffer=16384 --num-conns=10000 --num-calls=1
alloced_sd_to_conn = 2048
using connection 3
using connection 3
using connection 5
using connection 5
using connection 6
using connection 6
using connection 7
using connection 7
using connection 8
using connection 8
using connection 9
using connection 9
using connection 10
using connection 10
using connection 11
using connection 11
using connection 12
using connection 12
using connection 13
using connection 13
using connection 14
using connection 14
using connection 15
using connection 15
using connection 16
using connection 16
using connection 17
using connection 17
using connection 18
using connection 18
using connection 19
using connection 19
using connection 20
using connection 20
using connection 21
using connection 21
using connection 22
using connection 22
using connection 23
using connection 23
using connection 24
using connection 24
using connection 25
using connection 25
using connection 26
using connection 26
using connection 27
using connection 27
using connection 28
using connection 28
using connection 29
using connection 29
using connection 30
using connection 30
using connection 31
using connection 2624
Segmentation fault: 11
10:43 lawn-128-61-79-214:/tmp/httperf/build/src (master)$
```

So my initial thinking is: "2624 > 2048, so no wonder."  At least it's a starting point?

**Comment by refried** [comment]
P.S. Someone suggested to me that maybe the osx difference was clang vs gcc, but I did build it using gcc 5.3.0 as well, with no discernable change in behavior.

**Comment by erikarn** [comment]
Yeah, connection 2624 is garbage. That's the underlying problem. good catch!

ok, I'll go fire up some simple node.js setup locally and see what's going
on.



-adrian

**Comment by erikarn** [comment]
Oh, when printing out "using conn", can you also print out 'i' and
'bit' and 'n' and 'max_sd' on the same line? that should make it
obvious!


-adrian

**Comment by refried** [comment]
Sure, here are two runs; note the first one crashes without going over `alloced_to_sd`:
```
httperf --hog --timeout=1 --client=0/1 --server=localhost --port=11080 --uri=http://localhost:11080/fasor-api/v1/crc/meeting/1 --rate=1000 --send-buffer=4096 --recv-buffer=16384 --num-conns=10000 --num-calls=1
alloced_sd_to_conn = 2048
using conn sd = 3; i = 0, bit = 0, n = 0, max_sd = 3
using conn sd = 3; i = 0, bit = 0, n = 0, max_sd = 3
using conn sd = 5; i = 0, bit = 0, n = 0, max_sd = 5
using conn sd = 5; i = 0, bit = 0, n = 0, max_sd = 5
using conn sd = 6; i = 0, bit = 0, n = 0, max_sd = 6
using conn sd = 6; i = 0, bit = 0, n = 0, max_sd = 6
using conn sd = 7; i = 0, bit = 0, n = 0, max_sd = 7
using conn sd = 7; i = 0, bit = 0, n = 0, max_sd = 7
using conn sd = 8; i = 0, bit = 0, n = 0, max_sd = 8
using conn sd = 8; i = 0, bit = 0, n = 0, max_sd = 8
using conn sd = 9; i = 0, bit = 0, n = 0, max_sd = 9
using conn sd = 9; i = 0, bit = 0, n = 0, max_sd = 9
using conn sd = 10; i = 0, bit = 0, n = 0, max_sd = 10
using conn sd = 10; i = 0, bit = 0, n = 0, max_sd = 10
using conn sd = 11; i = 0, bit = 0, n = 0, max_sd = 11
using conn sd = 11; i = 0, bit = 0, n = 0, max_sd = 11
using conn sd = 12; i = 0, bit = 0, n = 0, max_sd = 13
using conn sd = 12; i = 0, bit = 0, n = 0, max_sd = 13
using conn sd = 13; i = 0, bit = 0, n = 0, max_sd = 13
using conn sd = 13; i = 0, bit = 0, n = 0, max_sd = 13
using conn sd = 14; i = 0, bit = 0, n = 0, max_sd = 14
using conn sd = 14; i = 0, bit = 0, n = 0, max_sd = 14
using conn sd = 15; i = 0, bit = 0, n = 0, max_sd = 15
using conn sd = 15; i = 0, bit = 0, n = 0, max_sd = 15
using conn sd = 16; i = 0, bit = 0, n = 0, max_sd = 16
using conn sd = 16; i = 0, bit = 0, n = 0, max_sd = 16
using conn sd = 17; i = 0, bit = 0, n = 0, max_sd = 17
using conn sd = 17; i = 0, bit = 0, n = 0, max_sd = 17
using conn sd = 18; i = 0, bit = 0, n = 0, max_sd = 18
using conn sd = 18; i = 0, bit = 0, n = 0, max_sd = 18
using conn sd = 19; i = 0, bit = 0, n = 0, max_sd = 19
using conn sd = 19; i = 0, bit = 0, n = 0, max_sd = 19
using conn sd = 20; i = 0, bit = 0, n = 0, max_sd = 20
using conn sd = 20; i = 0, bit = 0, n = 0, max_sd = 20
using conn sd = 21; i = 0, bit = 0, n = 0, max_sd = 21
using conn sd = 21; i = 0, bit = 0, n = 0, max_sd = 21
using conn sd = 22; i = 0, bit = 0, n = 0, max_sd = 22
using conn sd = 22; i = 0, bit = 0, n = 0, max_sd = 22
using conn sd = 23; i = 0, bit = 0, n = 0, max_sd = 23
using conn sd = 23; i = 0, bit = 0, n = 0, max_sd = 23
using conn sd = 24; i = 0, bit = 0, n = 0, max_sd = 24
using conn sd = 24; i = 0, bit = 0, n = 0, max_sd = 25
using conn sd = 25; i = 0, bit = 0, n = 0, max_sd = 25
using conn sd = 25; i = 0, bit = 0, n = 0, max_sd = 25
using conn sd = 26; i = 0, bit = 0, n = 0, max_sd = 26
using conn sd = 26; i = 0, bit = 0, n = 0, max_sd = 26
using conn sd = 27; i = 0, bit = 0, n = 0, max_sd = 27
using conn sd = 27; i = 0, bit = 0, n = 0, max_sd = 27
using conn sd = 28; i = 0, bit = 0, n = 0, max_sd = 28
using conn sd = 28; i = 0, bit = 0, n = 0, max_sd = 28
using conn sd = 29; i = 0, bit = 0, n = 0, max_sd = 29
using conn sd = 29; i = 0, bit = 0, n = 0, max_sd = 29
using conn sd = 30; i = 0, bit = 0, n = 0, max_sd = 30
using conn sd = 30; i = 0, bit = 0, n = 0, max_sd = 30
using conn sd = 31; i = 0, bit = 0, n = 0, max_sd = 31
using conn sd = 1055; i = 0, bit = 0, n = -1024, max_sd = 31
Segmentation fault: 11
```

Second one:
```
httperf --hog --timeout=1 --client=0/1 --server=localhost --port=11080 --uri=http://localhost:11080/fasor-api/v1/crc/meeting/1 --rate=1000 --send-buffer=4096 --recv-buffer=16384 --num-conns=10000 --num-calls=1
alloced_sd_to_conn = 2048
using conn sd = 3; i = 0, bit = 0, n = 0, max_sd = 3
using conn sd = 3; i = 0, bit = 0, n = 0, max_sd = 3
using conn sd = 5; i = 0, bit = 0, n = 0, max_sd = 5
using conn sd = 5; i = 0, bit = 0, n = 0, max_sd = 5
using conn sd = 6; i = 0, bit = 0, n = 0, max_sd = 6
using conn sd = 6; i = 0, bit = 0, n = 0, max_sd = 6
using conn sd = 7; i = 0, bit = 0, n = 0, max_sd = 7
using conn sd = 7; i = 0, bit = 0, n = 0, max_sd = 7
using conn sd = 8; i = 0, bit = 0, n = 0, max_sd = 8
using conn sd = 8; i = 0, bit = 0, n = 0, max_sd = 8
using conn sd = 9; i = 0, bit = 0, n = 0, max_sd = 9
using conn sd = 9; i = 0, bit = 0, n = 0, max_sd = 9
using conn sd = 10; i = 0, bit = 0, n = 0, max_sd = 10
using conn sd = 10; i = 0, bit = 0, n = 0, max_sd = 10
using conn sd = 11; i = 0, bit = 0, n = 0, max_sd = 11
using conn sd = 11; i = 0, bit = 0, n = 0, max_sd = 11
using conn sd = 12; i = 0, bit = 0, n = 0, max_sd = 12
using conn sd = 12; i = 0, bit = 0, n = 0, max_sd = 12
using conn sd = 13; i = 0, bit = 0, n = 0, max_sd = 13
using conn sd = 13; i = 0, bit = 0, n = 0, max_sd = 13
using conn sd = 14; i = 0, bit = 0, n = 0, max_sd = 14
using conn sd = 14; i = 0, bit = 0, n = 0, max_sd = 14
using conn sd = 15; i = 0, bit = 0, n = 0, max_sd = 15
using conn sd = 15; i = 0, bit = 0, n = 0, max_sd = 15
using conn sd = 16; i = 0, bit = 0, n = 0, max_sd = 16
using conn sd = 16; i = 0, bit = 0, n = 0, max_sd = 16
using conn sd = 17; i = 0, bit = 0, n = 0, max_sd = 17
using conn sd = 17; i = 0, bit = 0, n = 0, max_sd = 17
using conn sd = 18; i = 0, bit = 0, n = 0, max_sd = 18
using conn sd = 18; i = 0, bit = 0, n = 0, max_sd = 18
using conn sd = 19; i = 0, bit = 0, n = 0, max_sd = 19
using conn sd = 19; i = 0, bit = 0, n = 0, max_sd = 19
using conn sd = 20; i = 0, bit = 0, n = 0, max_sd = 20
using conn sd = 20; i = 0, bit = 0, n = 0, max_sd = 20
using conn sd = 21; i = 0, bit = 0, n = 0, max_sd = 21
using conn sd = 21; i = 0, bit = 0, n = 0, max_sd = 22
using conn sd = 22; i = 0, bit = 0, n = 0, max_sd = 22
using conn sd = 22; i = 0, bit = 0, n = 0, max_sd = 22
using conn sd = 23; i = 0, bit = 0, n = 0, max_sd = 23
using conn sd = 23; i = 0, bit = 0, n = 0, max_sd = 23
using conn sd = 24; i = 0, bit = 0, n = 0, max_sd = 24
using conn sd = 24; i = 0, bit = 0, n = 0, max_sd = 24
using conn sd = 25; i = 0, bit = 0, n = 0, max_sd = 25
using conn sd = 25; i = 0, bit = 0, n = 0, max_sd = 25
using conn sd = 26; i = 0, bit = 0, n = 0, max_sd = 26
using conn sd = 26; i = 0, bit = 0, n = 0, max_sd = 26
using conn sd = 27; i = 0, bit = 0, n = 0, max_sd = 27
using conn sd = 27; i = 0, bit = 0, n = 0, max_sd = 27
using conn sd = 28; i = 0, bit = 0, n = 0, max_sd = 28
using conn sd = 28; i = 0, bit = 0, n = 0, max_sd = 28
using conn sd = 29; i = 0, bit = 0, n = 0, max_sd = 29
using conn sd = 29; i = 0, bit = 0, n = 0, max_sd = 29
using conn sd = 30; i = 0, bit = 0, n = 0, max_sd = 30
using conn sd = 30; i = 0, bit = 0, n = 0, max_sd = 30
using conn sd = 31; i = 0, bit = 0, n = 0, max_sd = 31
using conn sd = 2624; i = 0, bit = 0, n = -2593, max_sd = 31
Segmentation fault: 11
```

**Comment by erikarn** [comment]
Ok, I've pushed some untested (sigh, no autoconf/automake on my macbook atm
:( ) code into github in the ahc_fix_select branch.

I'm going to undo the uhm, "smart" select() logic and eventually replace it
with poll logic for people who want it to behave better with many FDs.

Please compile it and let me know if it fails to compile or run and I'll
fix it up.

Thanks!


-a

**Comment by refried** [comment]
Fails to compile:
```
gcc-5 -DHAVE_CONFIG_H -I. -I../../src -I..    -I../../src -I../../src/gen -I../../src/lib -I../../src/stat -g -O0 -D_DARWIN_UNLIMITED_SELECT -MT core.o -MD -MP -MF .deps/core.Tpo -c -o core.o ../../src/core.c
../../src/core.c: In function 'core_loop':
../../src/core.c:1507:6: error: 'min_i' undeclared (first use in this function)
      min_i = min_sd / NFDBITS;
      ^
../../src/core.c:1507:6: note: each undeclared identifier is reported only once for each function it appears in
../../src/core.c:1508:6: error: 'max_i' undeclared (first use in this function)
      max_i = max_sd / NFDBITS;
      ^
```

**Comment by erikarn** [comment]
Ok, fixed, try again!


-adrian

**Comment by refried** [comment]
Also it never calls `check_conn()`! `is_readable`, `is_writable`, always 0 until it crashes :)

**Comment by erikarn** [comment]
It's still crashing? Hm!

Ok, try updating now. I was using 'i' instead of 'sd' for the loop, so it
never checked anything.



-adrian

**Comment by refried** [comment]
Better, but still crashing;  what do you think about this?

```
14:14 lawn-128-61-79-214:/tmp/httperf/build/src (ahc_fix_select)$ valgrind -q ./httperf --hog --server localhost --port 11080 --uri http://localhost:11080/fasor-api/v1/crc/attendee --num-conn 10000 --ra 1000 --timeout 10
httperf --hog --timeout=10 --client=0/1 --server=localhost --port=11080 --uri=http://localhost:11080/fasor-api/v1/crc/attendee --rate=1000 --send-buffer=4096 --recv-buffer=16384 --num-conns=10000 --num-calls=1
--17001-- UNKNOWN mach_msg unhandled MACH_SEND_TRAILER option
--17001-- UNKNOWN mach_msg unhandled MACH_SEND_TRAILER option (repeated 2 times)
--17001-- UNKNOWN mach_msg unhandled MACH_SEND_TRAILER option (repeated 4 times)
--17001-- UNKNOWN mach_msg unhandled MACH_SEND_TRAILER option (repeated 8 times)
==17001== Conditional jump or move depends on uninitialised value(s)
==17001==    at 0x10000798B: core_loop (core.c:1525)
==17001== 
==17001== Syscall param select(readfds) points to uninitialised byte(s)
==17001==    at 0x10056307A: select$DARWIN_EXTSN (in /usr/lib/system/libsystem_kernel.dylib)
==17001==    by 0x1000078F7: core_loop (core.c:1509)
==17001==  Address 0x104898898 is on thread 1's stack
==17001== 
httperf: connection failed with unexpected error 57
==17001== Syscall param select(writefds) points to uninitialised byte(s)
==17001==    at 0x10056307A: select$DARWIN_EXTSN (in /usr/lib/system/libsystem_kernel.dylib)
==17001==    by 0x1000078F7: core_loop (core.c:1509)
==17001==  Address 0x104898898 is on thread 1's stack
==17001== 
==17001== Conditional jump or move depends on uninitialised value(s)
==17001==    at 0x1000079C7: core_loop (core.c:1526)
==17001== 
==17001== Jump to the invalid address stated on the next line
==17001==    at 0x0: ???
==17001==    by 0x100004CC7: object_new (object.c:167)
==17001==    by 0x1000090CC: make_conn (conn_rate.c:73)
==17001==    by 0x100009880: tick (rate.c:117)
==17001==    by 0x100008BDF: timer_has_expired (timer.c:185)
==17001==    by 0x10000E3C6: list_for_each (list.c:150)
==17001==    by 0x100008C58: timer_tick (timer.c:214)
==17001==    by 0x100007728: core_loop (core.c:1504)
==17001==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==17001== 
==17001== 
==17001== Process terminating with default action of signal 11 (SIGSEGV)
==17001==  Bad permissions for mapped region at address 0x0
==17001==    at 0x0: ???
==17001==    by 0x100004CC7: object_new (object.c:167)
==17001==    by 0x1000090CC: make_conn (conn_rate.c:73)
==17001==    by 0x100009880: tick (rate.c:117)
==17001==    by 0x100008BDF: timer_has_expired (timer.c:185)
==17001==    by 0x10000E3C6: list_for_each (list.c:150)
==17001==    by 0x100008C58: timer_tick (timer.c:214)
==17001==    by 0x100007728: core_loop (core.c:1504)
Segmentation fault: 11
```

**Comment by refried** [comment]
Sorry, the line numbers may have been wrong in the previous one due to my inserted debug statements. Here's with a vanilla copy:
```
valgrind -q ./httperf --hog --server localhost --port 11080 --uri http://localhost:11080/fasor-api/v1/crc/attendee --num-conn 10000 --ra 1000 --timeout 10
httperf --hog --timeout=10 --client=0/1 --server=localhost --port=11080 --uri=http://localhost:11080/fasor-api/v1/crc/attendee --rate=1000 --send-buffer=4096 --recv-buffer=16384 --num-conns=10000 --num-calls=1
--17149-- UNKNOWN mach_msg unhandled MACH_SEND_TRAILER option
--17149-- UNKNOWN mach_msg unhandled MACH_SEND_TRAILER option (repeated 2 times)
--17149-- UNKNOWN mach_msg unhandled MACH_SEND_TRAILER option (repeated 4 times)
--17149-- UNKNOWN mach_msg unhandled MACH_SEND_TRAILER option (repeated 8 times)
==17149== Syscall param select(readfds) points to uninitialised byte(s)
==17149==    at 0x10056307A: select$DARWIN_EXTSN (in /usr/lib/system/libsystem_kernel.dylib)
==17149==    by 0x1000078F7: core_loop (core.c:1509)
==17149==  Address 0x104898898 is on thread 1's stack
==17149== 
==17149== Conditional jump or move depends on uninitialised value(s)
==17149==    at 0x10000798B: core_loop (core.c:1525)
==17149== 
httperf: connection failed with unexpected error 57
==17149== Syscall param select(writefds) points to uninitialised byte(s)
==17149==    at 0x10056307A: select$DARWIN_EXTSN (in /usr/lib/system/libsystem_kernel.dylib)
==17149==    by 0x1000078F7: core_loop (core.c:1509)
==17149==  Address 0x104898898 is on thread 1's stack
==17149== 
==17149== Conditional jump or move depends on uninitialised value(s)
==17149==    at 0x1000079C7: core_loop (core.c:1526)
==17149== 
==17149== Jump to the invalid address stated on the next line
==17149==    at 0x0: ???
==17149==    by 0x100004CC7: object_new (object.c:167)
==17149==    by 0x1000090CC: make_conn (conn_rate.c:73)
==17149==    by 0x100009880: tick (rate.c:117)
==17149==    by 0x100008BDF: timer_has_expired (timer.c:185)
==17149==    by 0x10000E3C6: list_for_each (list.c:150)
==17149==    by 0x100008C58: timer_tick (timer.c:214)
==17149==    by 0x100007728: core_loop (core.c:1504)
==17149==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==17149== 
==17149== 
==17149== Process terminating with default action of signal 11 (SIGSEGV)
==17149==  Bad permissions for mapped region at address 0x0
==17149==    at 0x0: ???
==17149==    by 0x100004CC7: object_new (object.c:167)
==17149==    by 0x1000090CC: make_conn (conn_rate.c:73)
==17149==    by 0x100009880: tick (rate.c:117)
==17149==    by 0x100008BDF: timer_has_expired (timer.c:185)
==17149==    by 0x10000E3C6: list_for_each (list.c:150)
==17149==    by 0x100008C58: timer_tick (timer.c:214)
==17149==    by 0x100007728: core_loop (core.c:1504)
Segmentation fault: 11
```

**Comment by refried** [comment]
Sorry, I know this is hard.  If you want to add debug statements to your branch, I'm happy to run them.  Not sure the ones I would insert are relevant anymore.

**Comment by refried** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000100007bc3 in event_signal (type=EV_CONN_NEW, obj=0x100960400, arg=...) at ../../src/localevent.c:123
#2  0x0000000100004cc8 in object_new (type=OBJ_CONN) at ../../src/object.c:167
#3  0x00000001000090cd in make_conn (arg=...) at ../../../src/gen/conn_rate.c:73
#4  0x0000000100009881 in tick (t=0x10020f5c0, arg=...) at ../../../src/gen/rate.c:117
#5  0x0000000100008be0 in timer_has_expired (a=...) at ../../src/timer.c:185
#6  0x000000010000e3c7 in list_for_each (l=0x1003002d0, action=0x100008b69 <timer_has_expired>) at ../../../src/lib/list.c:150
#7  0x0000000100008c59 in timer_tick () at ../../src/timer.c:214
#8  0x0000000100007a23 in core_loop () at ../../src/core.c:1535
#9  0x0000000000000000 in ?? ()
(gdb) up
#1  0x0000000100007bc3 in event_signal (type=EV_CONN_NEW, obj=0x100960400, arg=...) at ../../src/localevent.c:123
123	    (*c->op) (type, obj, c->arg, arg);
(gdb) p c->op
$2 = (Event_Handler) 0x0
```

**Comment by erikarn** [comment]
Hi,

Okay, can you add some prints to see which sd's are being serviced (ie,
we're calling check_conn() on them) - I want to see if we're still seeing
the invalid numbers.


-a

**Comment by refried** [comment]
There's a lot of output! https://gist.github.com/refried/ae6a5d34aa8a104ac23cfaef3468557e

`sd` doesn't exceed `alloced_sd_to_conn`, but the program ends with
```
httperf.core_loop: select failed: Bad file descriptor
```

**Comment by refried** [comment]
Or sometimes:
```
<snip>
check_conn(sd = 2150, is_readable = 0, is_writable = 1)
check_conn(sd = 2155, is_readable = 0, is_writable = 1)
alloced_sd_to_conn = 6144
Segmentation fault: 11
```

**Comment by refried** [comment]
also:
```
check_conn(sd = 2155, is_readable = 0, is_writable = 1)
alloced_sd_to_conn = 6144
httperf.core_loop: select failed: Bad file descriptor
max_sd + 1 = 4664, readable = -1, writable = 64, n = 2058691040
```

**Comment by erikarn** [comment]
ok, n is just wrong there. it's like it's getting corrupted or set to
something garbage. Just replace SYSCALL(n = select... ) with just the 'n =
select();' bits. I kinda don't trust that macro right now.


-adrian

**Comment by refried** [comment]
Alright cool.  I just left that computer for the day but I'll give that a shot tomorrow.  Thanks!

**Comment by erikarn** [comment]
Ok, thanks!

The select() code isn't bounds checking anything. I just pushed an update -
the default FD_SETSIZE on macosx isn't all that big and it's easy to
overflow it.

I've added a check - see if that fixes it. It should now warn if we start
trying to create connections above the FD_SETSIZE limit.
I'll see if I can implement poll() soon which would remove the fd number
limitation.



-adrian

**Comment by refried** [comment]
Ok, with the latest it didn't crash, but it did have lots of `sd > FD_SETSIZE (1024)` errors.

```
Maximum connect burst length: 13

Total: connections 5000 requests 4761 replies 57 test-duration 50.806 s

Connection rate: 98.4 conn/s (10.2 ms/conn, <=1022 concurrent connections)
Connection time [ms]: min 1463.4 avg 2544.2 max 5344.3 median 1937.5 stddev 1290.8
Connection time [ms]: connect 26.2
Connection length [replies/conn]: 1.000

Request rate: 93.7 req/s (10.7 ms/req)
Request size [B]: 109.0

Reply rate [replies/s]: min 0.0 avg 1.1 max 11.4 stddev 3.6 (10 samples)
Reply time [ms]: response 2543.0 transfer 0.0
Reply size [B]: header 142.0 content 14.0 footer 0.0 (total 156.0)
Reply status: 1xx=0 2xx=0 3xx=0 4xx=57 5xx=0

CPU time [s]: user 5.09 system 44.69 (user 10.0% system 88.0% total 98.0%)
Net I/O: 10.1 KB/s (0.1*10^6 bps)

Errors: total 5842 client-timo 4452 socket-timo 0 connrefused 0 connreset 491
Errors: fd-unavail 0 addrunavail 0 ftab-full 0 other 899
```

**Comment by refried** [comment]
Maybe this will help? http://stackoverflow.com/a/27065458/310162

**Comment by erikarn** [comment]
Hi,

Right - poll() should be used here, not select(), at the very least.

Just redefine FD_SETSIZE in core.c (up the top, I commented it out) to like
2048 and see if it still behaves fine. If so, then yeah, I'll chalk this
bug up to "noone freaking bounds checked the maximum FD" and I'll go commit
a fix to that shortly.



-adrian

**Comment by refried** [comment]
On OS X 10.11.4 at least, redefining FD_SETSIZE doesn't seem to take:
uncommented:
```c
#define	FD_SETSIZE	2048
```
output
```
httperf.core_loop: select failed: Invalid argument
max_sd+1 = 1025, n = -1
```

**Comment by erikarn** [comment]
Right, needs to be converted to poll() then


-a

**Comment by joolzg** [comment]
Anybody working on this, im trying to test a new server and hitting the >1024 open handles, running this with a timeout of 175 seconds and 64 connections per second, once i go over 1024 handles i get the select error. Reading the we it says this should be converted to poll()

**Comment by erikarn** [comment]
I'm not working on it at the moment, sorry. Converting it to poll()
shouldn't be hard though!


-a
